### DISCUSSION TITLE
Serve multiple models with llamacpp server

### DISCUSSION THREAD

**Discussion by PierreCarceller** [ggml-org/llama.cpp#10431] [Q&A]
Is there a way to serve more than one model at the same time? (I don't think so).
Are there any plans to add this feature?

**Comment by ExtReMLapin** [comment]
https://github.com/abetlen/llama-cpp-python/pull/931

or just start multiple instance lol

**Reply by PierreCarceller** [reply]
I saw the link you shared but I'd like to use llamacpp server. Not llamacpp-python server.

"or just start multiple instance lol" -> For sure it's a solution that works, but it's a pain to have to manage several instances...

**Reply by magikRUKKOLA** [reply]
@ExtReMLapin @PierreCarceller 

The matters explained in great detail over here: https://github.com/ggml-org/llama.cpp/discussions/10431#discussioncomment-14941454

@ExtReMLapin is absolutely right.

The discussion can be safely closed, I do approve.

**Comment by 3Simplex** [comment]
I start each model in a separate server instance using a new port for each model. Then I make an API call to any running server providing the array of messages intended for that model. I can also use the very nice webUI that @ngxson made for any running server!
![image](https://github.com/user-attachments/assets/2f2ddc80-b740-4eba-95c1-a15599628667)

**Reply by magikRUKKOLA** [reply]
+1

in addition:  https://github.com/ggml-org/llama.cpp/discussions/10431#discussioncomment-14941454

**Comment by kth8** [comment]
I saw this project on r/LocalLLaMA as a workaround: https://github.com/mostlygeek/llama-swap

**Comment by Gomez12** [comment]
I would say either add a proxy server in front of it, or just use a project like llama-swap. Then you can just have all the config options etc per server.

The proxy would just need some simple routing, some simple queuing per server and options like trying to start new model as second server (if you have the memory available) and then you can just reuse all server options.
It also opens up possibilities like reusing the same model with multiple context sizes etc.

**Comment by jukofyork** [comment]
I haven't tried using it, but there is also this:

https://github.com/perk11/large-model-proxy

It looks like you can run multiple backend even and then have them unload automatically using least recently used, etc.

**Comment by Cronvs** [comment]
Still seems like a nice feature, if the will to implement it is there.

**Comment by ocean1ee1** [comment]
I'm learning to use llama.cpp... Have a similar need. Basically I would like to set up some rules for different prompt types and decide to use different models on one server.

Still not sure weather currently it's possible the original llama-server application supports to load / swap different models via an api call to specific a model path or not.

for example, I cannot change a model via the below call even will get a success response, maybe my usage is not correct.
curl --url http://127.0.0.1:8080/props -d '{"model_path":"/model/xxxx.gguf"}' -X POST

**Comment by braycarla** [comment]
You can serve multiple models with server by loading them simultaneously and specifying the model in API requests. For more details visit llamacpp.info

**Comment by ocean1ee1** [comment]
@braycarla 

Could you please share a link that contains how to load multiple models?

I went though some articles, however did not figure out how to pass multiple models. 😢

Also tried the below commands, all did not work.

-  ./llama-server -m ./a.gguf -m ./b.gguf
-  ./llama-server -m ./a.gguf **,** ./b.gguf
-  ./llama-server -m ./a.gguf **;** ./b.gguf
-  ./llama-server -m ./a.gguf ./b.gguf

**Comment by braycarla** [comment]
To serve multiple models using llama.cpp with llamacpp .info server, you need to run the server in a way that supports multiple models. Here’s how you can do it:

**Comment by yazon** [comment]
You can use FlexLLama to handle multiple models: https://github.com/yazon/flexllama

**Comment by jukofyork** [comment]
I knocked something together yesterday as I was getting suspicious that the front-ends were adding sampler parameters for my `llama.cpp` drafted models and screwing them up:

https://github.com/ggml-org/llama.cpp/discussions/14129
https://github.com/ggml-org/llama.cpp/issues/10819

it turned out they weren't so haven't added the sampler filtering yet, but after some playing about I realised it was way simpler to just expose a single end-point on port 3000 than have to add separate endpoints and API keys over and over (or messing about trying to get rid of the 400+ openrouter models you ***don't*** want!):

```toml
[LOCAL-SERVER-1]
endpoint = "http://192.168.1.100"
ports = [8080, 8081]

[LOCAL-SERVER-2]
endpoint = "http://192.168.1.101"
ports = [8080, 8081]

[OpenRouter]
endpoint = "https://openrouter.ai/api/v1"
api_key = "<YOUR KEY HERE>"
models = ["anthropic/claude-3.5-sonnet", "anthropic/claude-3-opus", "google/gemini-pro", "meta-llama/llama-3.1-405b"]

[OpenAI]
endpoint = "https://api.openai.com/v1"
api_key = "<YOUR KEY HERE>"
models = ["gpt-4", "gpt-4-turbo", "o1-preview"]

[DeepSeek]
endpoint = "https://api.deepseek.com/v1"
api_key = "<YOUR KEY HERE>"
models = ["deepseek-chat", "deepseek-coder"]
```

and it's probably quite useful in its own right:

https://github.com/jukofyork/llm-proxy

(it's written in Java but the same logic could easily be ported to GO or C++ using `libcurl` or `Boost.Beast`, etc)

I also made it so you can select `llama.cpp` models from the non-OpenAI endpoints by passing the model name as the key (useful for `mikupad` or other tools that use the extra functionality of the `llama.cpp` endpoints).
