### ISSUE TITLE
[Tracker] Docker build fails on CI for arm64

### ISSUE THREAD

**Issue by ngxson** [ggml-org/llama.cpp#11888]
Tracker for upstream issue: https://github.com/docker/build-push-action/issues/1309

At the time of writing this issue, this has been failing for the past 3 days: https://github.com/ggml-org/llama.cpp/actions/workflows/docker.yml

It was fixed in https://github.com/ggml-org/llama.cpp/pull/11472 but now the problem came back.

CC @ggerganov @slaren for visibility

**Comment by ggerganov** [comment]
I noticed that and these failures are actually now caused by a different issue:

https://github.com/ggml-org/llama.cpp/actions/runs/13322407195/job/37209322813#step:8:2252

Googling a bit:

https://github.com/tonistiigi/binfmt/issues/240

**Comment by ngxson** [comment]
I'm running a CI with `tonistiigi/binfmt:qemu-v7.0.0-28` on my fork: https://github.com/ngxson/llama.cpp/actions/runs/13346220830/job/37276975481

Will make a PR if it fixes the issue

**Comment by ngxson** [comment]
Seems like ARM64 build still fail no matter what we tried, can we move the ARM64 build to a self-hosted runner @ggerganov ?

**Comment by ggerganov** [comment]
Which one is the failing build now?

**Comment by ggerganov** [comment]
I see. Did you find any information what is the cause this time? Maybe it will be resolved soon.

**Comment by ngxson** [comment]
I have been applying many suggestions from https://github.com/tonistiigi/binfmt/issues/215 but the issue still come back after a while.

On second thought, I think we could try using arm64 hosted runner to get rid of the emulation. What I don't know is that will ARM extensions like VFP or NEON be enabled in build time.

**Comment by AlexTMjugador** [comment]
> On second thought, I think we could try using arm64 hosted runner to get rid of the emulation. What I don't know is that will ARM extensions like VFP or NEON be enabled in build time.

For what it's worth, GitHub [confirmed the usage of Azure VMs of the Dpdsv5 series for their cloud-hosted runners](https://github.com/orgs/community/discussions/148648#discussioncomment-12205917). [The Ampere Altra processors used in these are based on the ARM Neoverse platform](https://amperecomputing.com/press/hetzner-first-european-hoster-with-ampere-altra-based-dedicated-servers), and are [specified to conform to ARMv8.2-A](https://amperecomputing.com/briefs/ampere-altra-family-product-brief). The Neoverse platform is based on a beefed-up [Cortex-A76](https://en.wikipedia.org/wiki/ARM_Cortex-A76) at minimum, which has VFP and NEON extensions as a baseline requirement. In fact, all ARMv8-A+ CPUs have SIMD extensions.

Basically, all of the paragraph above is to say that yes, building for the same architecture that GitHub ARM runners execute on will most likely make use of the extensions you'd expect from capable ARM CPUs. (Notably, all Apple Mx CPUs support at least ARMv8.5-A, so they may have some additional useful instructions for ML, but given that commonly deployed ARM server CPUs have lagged behind a little when it comes to extension support compared to Apple, I think that a generic ARM Docker image should not bother forcing the use of those extensions anyway.)

**Comment by AlexTMjugador** [comment]
So I tried to build `cpu.Dockerfile` on a native Neoverse platform server, and my results were quite positive: everything worked as intended.

And I don't think we're leaving any performance on the table for any ARM CPU, because I realized specialized GGML code is built for all ARM CPU variants since https://github.com/ggml-org/llama.cpp/commit/646944cfa8961afd914dd6637739b3cda9a72e11.

The only gotcha I found is that building for ARMv9.2 requires GCC 14, as described on https://github.com/ggml-org/llama.cpp/issues/17403, which [is notably absent from Ubuntu 22.04's repositories](https://documentation.ubuntu.com/ubuntu-for-developers/reference/availability/gcc/). Therefore, I had to bump the `UBUNTU_VERSION` build argument to `25.10` (Ubuntu 24.04 LTS could also work here, but unlike Ubuntu 25, it does not use GCC 14 by default, so I opted to bump the whole distro version for simplicity).

For completeness, here's the Docker Compose file I used to test the above, and that people can use to get a working ARM llama.cpp Docker image today when building from a ARM host:

```yaml
services:
  llamacpp-server:
    build:
      dockerfile: .devops/cpu.Dockerfile
      context: https://github.com/ggml-org/llama.cpp.git
      args:
        # Required to work around https://github.com/ggml-org/llama.cpp/issues/17403
        UBUNTU_VERSION: "25.10"
```

**Comment by jriberg** [comment]
Any love for this issue to get it into main?

**Comment by papamoose** [comment]
I've been using a self hosted runner to build arm64 images my branch here: https://github.com/papamoose/llama.cpp/tree/papamoose/cuda_arm64_docker_build

also related: !17983

I'm not suggesting my solution is correct only that the images have been building and working in this way for me.

**Comment by ehfd** [comment]
I affirm that the below (using GCC 14) works well for `cuda-new.Dockerfile`. I believe that `aarch64` builds for CUDA can be enabled as well, and it will help a lot.

```yaml
build-and-push-job:
  stage: build-and-push
  variables:
    LLAMA_CPP_REF: "b8477"
  script:
  - cd $CI_PROJECT_DIR
  - git clone https://github.com/ggml-org/llama.cpp.git
  - cd llama.cpp
  - git checkout $LLAMA_CPP_REF
  - |
  - sed -i 's/apt-get install -y build-essential/apt-get install -y gcc-14 g++-14 build-essential/g' .devops/cuda-new.Dockerfile
  - sed -i '/apt-get install -y gcc-14 g++-14 build-essential/a ENV CC=gcc-14 CXX=g++-14 CUDAHOSTCXX=g++-14' .devops/cuda-new.Dockerfile
  - |
    # Build cuda-new.Dockerfile
    docker buildx build \
      -f .devops/cuda-new.Dockerfile \
      --push \
      --provenance=false \
      --platform linux/arm64 \
      --target full \
      -t $CI_REGISTRY_IMAGE:latest \
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
      .
```
