### ISSUE TITLE
Feature Proposal: Server Model Switching at Runtime

### ISSUE THREAD

**Issue by christopherthompson81** [ggml-org/llama.cpp#13027]
### Prerequisites

- [x] I am running the latest code. Mention the version if possible as well.
- [x] I carefully followed the [README.md](https://github.com/ggml-org/llama.cpp/blob/master/README.md).
- [x] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggml-org/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

I would like to adapt the server (or create an alternate server) so that it is more suited to being changed during runtime.  My primary goal in doing so is to be able to switch models on the fly.

### Motivation

In local inference, I find that no single model is best for all tasks and I switch between models frequently using TabbyAPI. I would like to be able to have this functionality available directly in llama.cpp to be able to make use of GGUF files and the llama.cpp ecosystem.

### Possible Implementation

Specifically, I want to be able to:

* Start the server without a model loaded and be functional in a state without models
* Have multiple models loaded concurrently
* Offer a /models endpoint to:
    * List available models (GET:/models)
    * Get details about a specific model (GET:/models/{model_id})
    * List available draft models (GET:/models/draft_models)
    * Get details about a specific draft model (GET:/models/draft_models/{model_id})
    * Change model routing settings (POST:/models)
    * List loaded models and default model routing (GET:/models/status)
    * Load models (POST:/models/load)
    * Unload models (POST:/models/unload)

This may also require similar endpoints for loading and unloading LoRAs, embeddings, and other factors. For example, I may want to be able to monitor GPU status for available VRAM and use that as a check before loading models.

Before I get started, I wanted to solicit some feedback from the community on endpoint names and required features. Does anyone have any thoughts about this, the names, if there are negative impacts, or anything else?

**Comment by TheNexter** [comment]
Enjoy llamaswap 😄 

Llamaswap use llamacpp + a small proxy to manage llamacpp (in my case vulkan version compile)

config.yaml
```
healthCheckTimeout: 5000
logRequests: true

models:
  gemma-3-1b:
    proxy: http://127.0.0.1:9999
    cmd: /app/llama-server -m /Models/google_gemma-3-1b-it-Q4_K_M.gguf --port 9999 --ctx-size 0 --gpu-layers 100 --temp 1.0 --top-k 64 --top-p 0.95 --flash-attn
    ttl: 3600

  gemma-3-12b:
    proxy: http://127.0.0.1:9999
    cmd: /app/llama-server -m /Models/google_gemma-3-12b-it-Q4_K_M.gguf --port 9999 --ctx-size 16384 --gpu-layers 15 --temp 1.0 --top-k 64 --top-p 0.95 --flash-attn
    ttl: 3600

  gemma-3-27b:
    proxy: http://127.0.0.1:9999
    cmd: /app/llama-server -m /Models/google_gemma-3-27b-it-Q4_K_M.gguf --port 9999 --ctx-size 16384 --gpu-layers 10 --temp 1.0 --top-k 64 --top-p 0.95 --flash-attn
    ttl: 3600
```

docker-compose.yml
```
services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:vulkan
    container_name: llama-swap
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri:/dev/dri
    volumes:
      - ./Models:/Models
      - ./config/Llama-swap/config.yaml:/app/config.yaml
    ports:
      - 8080:8080
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    volumes:
      - ./config/Open-webui:/app/backend/data
    depends_on:
      - llama-swap
    ports:
      - 9999:8080
    environment:
      - 'OPENAI_API_BASE_URL=http://llama-swap:8080'
    restart: unless-stopped
```
